In [212]:
import numpy as np
import pandas as pd

from datetime import datetime

In [213]:
#load in data
food_df = pd.read_csv("Diabetes_Data/log_data_fooddata.csv")
insulin_df = pd.read_csv("Diabetes_Data/log_data_insulindata.csv")
corrections_df = pd.read_csv("Diabetes_Data/log_data_correctionsdata.csv")

bg_df = pd.read_csv("Diabetes_Data/bs_data.csv")
hr_df = pd.read_csv("Diabetes_Data/hr_data.csv")

In [214]:
#CLEAN DATA FUNCTIONS
def clean_log_times(logname): 
    #extract date as column
    logname['date'] = [pd.Timestamp(k.split(' ')[0]) for k in logname['datetime']]
    #extract and clean time as column
    logname['time'] = [k.split(' ')[1] for k in logname['datetime']]
    logname['hour'] = [int(k.split(':')[0]) for k in logname['time']]
    logname['minute'] = [int(k.split(':')[1]) for k in logname['time']]
    #drop time and datetime
    logname = logname.drop(['time', 'datetime'], axis='columns')

    for k in range(len(logname['minute'])):
        min = logname['minute'][k]
        res = min % 5
        logname.at[k, 'minute'] = min-res if res < 3 else min+(5-res)
        
    logname = logname.groupby(by=['date', 'hour', 'minute']).sum().reset_index()
    return logname

def clean_sep_date_times(logname):
    logname['date'] = pd.to_datetime(logname['date'])
    logname['hour'] = [int(k.split(':')[0]) for k in logname['time']]
    logname['minute'] = [int(k.split(':')[1]) for k in logname['time']]
    logname = logname.drop('time', axis='columns')
    return logname

def combine_dfs(left_df, right_df):
    df = left_df.merge(right_df, on=['date', 'hour', 'minute'], how='outer')
    df = df.fillna(0)
    return df

In [215]:
datetime_list =  pd.date_range(
                        start=bg_df.date[len(bg_df)-1],
                        end=bg_df.date[0],
                        freq='5min').to_frame(index=False, name='datetime')

datetime_list['date'] = [str(k).split()[0] for k in datetime_list['datetime']]
datetime_list['time'] = [str(k).split()[1] for k in datetime_list['datetime']]

datetime_list = clean_sep_date_times(datetime_list)
datetime_list.drop('datetime', axis='columns', inplace=True)

In [216]:
#CLEAN FOOD DATA
food_df = clean_log_times(food_df)
food_df = food_df.drop(['servingAmount', 'servingId', 'id', 'foodId'], axis='columns')

In [217]:
#MERGE DATA
df = combine_dfs(datetime_list, food_df)

In [223]:
print(len(df))
print(food_df)

#i need to find datetimes that are not in my datetime list

5476
         date  hour  minute  calories   carbs     fat  fiber  protein   sugar
0  2021-11-22    13      20      2.00    0.07    0.04   0.00     0.21    0.00
1  2021-11-22    18      40   2260.00  209.00  124.00   5.00    84.00  110.00
2  2021-11-23     1      25    168.00   15.00    0.00   0.00     2.20    0.00
3  2021-11-23     2       0   1192.00  118.43   62.91  12.80    48.13    6.35
4  2021-11-23    17      45   1590.00  117.00   93.00   6.00    69.00    9.00
..        ...   ...     ...       ...     ...     ...    ...      ...     ...
85 2021-12-10     2      15     49.20    7.06    2.07   0.48     0.83    1.24
86 2021-12-10     2      20    128.00   10.00    0.00   0.00     1.40    0.00
87 2021-12-10    15      55    310.00   54.00    8.00   5.00     9.00    7.00
88 2021-12-10    21      20    630.00   61.00   32.00   4.00    27.00    8.00
89 2021-12-11     5       0    433.95   69.32   10.67   0.39    13.93   21.88

[90 rows x 9 columns]
0

In [144]:
#CLEAN BLOOD GLUCOSE DATA
bg_df = clean_sep_date_times(bg_df)

In [145]:
#MERGE DATA
df = combine_dfs(bg_df, food_df)
print(len(df))

5571

In [146]:
#CLEAN INSULIN DATA
insulin_df = clean_log_times(insulin_df)
insulin_df = insulin_df.drop(['id'], axis='columns')

#modify insulin ids so none are zero
insulin_df['insulinId'] = [k+1 for k in insulin_df['insulinId']]

insulin_df.rename(columns={'amount': 'insulin_amount'}, inplace=True)

In [147]:
#MERGE DATA
df = combine_dfs(df, insulin_df)
print(len(df))

5575

In [148]:
#CLEAN CORRECTIONS DATA
corrections_df = clean_log_times(corrections_df)
corrections_df = corrections_df.drop(['id', 'correctionId'], axis='columns')

corrections_df.rename(columns={'amount': 'corrs_amount'}, inplace=True)

In [149]:
#MERGE DATA
df = combine_dfs(df, corrections_df)
print(len(df))

5576

In [150]:
#CLEAN HEART RATE DATA
hr_df = clean_sep_date_times(hr_df)

In [151]:
#MERGE DATA
df = combine_dfs(df, hr_df)
df['weekday'] = [k.day_name() for k in df['date']]
print(len(df))

5621

In [153]:
print(len(df))
print(len(datetime_list))

df

5621
5473

,date,BS,BS_trend,hour,minute,calories,carbs,fat,fiber,protein,sugar,insulin_amount,insulinId,corrs_amount,hr,weekday
0,2021-12-11,90.0,-0.3,11,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saturday
1,2021-12-11,92.0,-0.3,11,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saturday
2,2021-12-11,94.0,0.1,11,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saturday
3,2021-12-11,95.0,-0.1,11,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saturday
4,2021-12-11,94.0,-0.2,11,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5616,2021-11-26,0.0,0.0,22,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,Friday
5617,2021-11-26,0.0,0.0,22,55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.0,Friday
5618,2021-11-26,0.0,0.0,23,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0,Friday
5619,2021-11-26,0.0,0.0,23,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0,Friday
5620,2021-11-26,0.0,0.0,23,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,Friday